//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.db {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.db.lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string btnContact {
            get {
                return ResourceManager.GetString("btnContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download report.
        /// </summary>
        internal static string btnReportdownload {
            get {
                return ResourceManager.GetString("btnReportdownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string btnTest {
            get {
                return ResourceManager.GetString("btnTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start verification.
        /// </summary>
        internal static string btnVerify {
            get {
                return ResourceManager.GetString("btnVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify further documents.
        /// </summary>
        internal static string btnVerifyanother {
            get {
                return ResourceManager.GetString("btnVerifyanother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string docReport {
            get {
                return ResourceManager.GetString("docReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail*.
        /// </summary>
        internal static string emailContact {
            get {
                return ResourceManager.GetString("emailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Algorithm.
        /// </summary>
        internal static string enkriptalg {
            get {
                return ResourceManager.GetString("enkriptalg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of signed file.
        /// </summary>
        internal static string filenameReport {
            get {
                return ResourceManager.GetString("filenameReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name*.
        /// </summary>
        internal static string FirstnameContact {
            get {
                return ResourceManager.GetString("FirstnameContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string firstnameReport {
            get {
                return ResourceManager.GetString("firstnameReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Algorithm.
        /// </summary>
        internal static string hashalg {
            get {
                return ResourceManager.GetString("hashalg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash value of signed data (SHA256).
        /// </summary>
        internal static string HashReport {
            get {
                return ResourceManager.GetString("HashReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGNATURE CHECK.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Data.
        /// </summary>
        internal static string headerTest {
            get {
                return ResourceManager.GetString("headerTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below you can contact us for every question, suggestion or concern. Please make sure to fill out all the fields marked with *..
        /// </summary>
        internal static string infoContact {
            get {
                return ResourceManager.GetString("infoContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature check.
        /// </summary>
        internal static string infoReport {
            get {
                return ResourceManager.GetString("infoReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For testing our service, if you have not digitally signed document, below you can download a document that you can use as a test. After you download the file you can go to the page for verification and check the downloaded document..
        /// </summary>
        internal static string infoTest {
            get {
                return ResourceManager.GetString("infoTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying verification reports:.
        /// </summary>
        internal static string InstrcDisplayingRes {
            get {
                return ResourceManager.GetString("InstrcDisplayingRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After completion the verification process will be presented the following report. This report shows if verification resulted valid and contains data for the signatory of the document and the issuer of the certificate. At the end of this report you have the &quot;Download report&quot; if you want to download this report (in PDF format), also you have the button &quot; Verify further documents &quot; if you want to check another document..
        /// </summary>
        internal static string InstrcDisplayingResText {
            get {
                return ResourceManager.GetString("InstrcDisplayingResText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use Signature Check:.
        /// </summary>
        internal static string InstrcHowToUse {
            get {
                return ResourceManager.GetString("InstrcHowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing the signature verification:.
        /// </summary>
        internal static string InstrcProcessingSig {
            get {
                return ResourceManager.GetString("InstrcProcessingSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After opening the website or by clicking the “Verify” menu opens the following site, which serves for upload signed document. Click on the “Choose file” and then select the document you want to upload, applies only to PDF signed documents. After selecting the document, click on the &quot;Start verification&quot; button. The process for verifying the signed document is initiated..
        /// </summary>
        internal static string InstrcProcessingSigText {
            get {
                return ResourceManager.GetString("InstrcProcessingSigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you receive the digitally signed documents or files, first save the signed document at a location you will easy remember later..
        /// </summary>
        internal static string InstrcReceivingText {
            get {
                return ResourceManager.GetString("InstrcReceivingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving signed documents &amp; data:.
        /// </summary>
        internal static string InstrcReceivingTitle {
            get {
                return ResourceManager.GetString("InstrcReceivingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country(C).
        /// </summary>
        internal static string issuerc {
            get {
                return ResourceManager.GetString("issuerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name(CN).
        /// </summary>
        internal static string issuercn {
            get {
                return ResourceManager.GetString("issuercn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info of certificate issuer.
        /// </summary>
        internal static string issuerinfo {
            get {
                return ResourceManager.GetString("issuerinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization(O).
        /// </summary>
        internal static string issuero {
            get {
                return ResourceManager.GetString("issuero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational unit(OU).
        /// </summary>
        internal static string issuerou {
            get {
                return ResourceManager.GetString("issuerou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name*.
        /// </summary>
        internal static string LastnameContact {
            get {
                return ResourceManager.GetString("LastnameContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string lastnameReport {
            get {
                return ResourceManager.GetString("lastnameReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string mnuContact {
            get {
                return ResourceManager.GetString("mnuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        internal static string mnuInstruction {
            get {
                return ResourceManager.GetString("mnuInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Data.
        /// </summary>
        internal static string mnuTest {
            get {
                return ResourceManager.GetString("mnuTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string mnuVerify {
            get {
                return ResourceManager.GetString("mnuVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message*.
        /// </summary>
        internal static string msgContact {
            get {
                return ResourceManager.GetString("msgContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Based on the Law on Information Society Services, Article 1 - Defines electronic documentation identical to Its traditional Legally counterpart in paper format..
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate serial number.
        /// </summary>
        internal static string serialnumber {
            get {
                return ResourceManager.GetString("serialnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate information.
        /// </summary>
        internal static string signerInfo {
            get {
                return ResourceManager.GetString("signerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signer.
        /// </summary>
        internal static string signerReport {
            get {
                return ResourceManager.GetString("signerReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing time.
        /// </summary>
        internal static string signingtime {
            get {
                return ResourceManager.GetString("signingtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of signed file.
        /// </summary>
        internal static string sizeReport {
            get {
                return ResourceManager.GetString("sizeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string subjectContact {
            get {
                return ResourceManager.GetString("subjectContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        internal static string telContact {
            get {
                return ResourceManager.GetString("telContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitally signed test document(signed_document.pdf).
        /// </summary>
        internal static string testDoc {
            get {
                return ResourceManager.GetString("testDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification date and time.
        /// </summary>
        internal static string TimeReport {
            get {
                return ResourceManager.GetString("TimeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document:.
        /// </summary>
        internal static string uploadDoc {
            get {
                return ResourceManager.GetString("uploadDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the digital signature of the document.
        /// </summary>
        internal static string uploadHeader {
            get {
                return ResourceManager.GetString("uploadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate valid from.
        /// </summary>
        internal static string validfrom {
            get {
                return ResourceManager.GetString("validfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate valid to.
        /// </summary>
        internal static string validto {
            get {
                return ResourceManager.GetString("validto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site for verification of digital signature, allows you to verify the digital signature of PDF documents for authenticity in only a few seconds. As a result you will have a report with the data of signatories, which report can be downloaded..
        /// </summary>
        internal static string welcomeParagraph {
            get {
                return ResourceManager.GetString("welcomeParagraph", resourceCulture);
            }
        }
    }
}
